### ISSUE TITLE
httpie doesn't work

### ISSUE THREAD

**Issue by mortenlj** [mortenlj/kafka-debug#1]
```
$ http
Traceback (most recent call last):
  File "/usr/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie==3.2.1', 'console_scripts', 'http')())
  File "/usr/lib/python3.10/site-packages/httpie/__main__.py", line 9, in main
    exit_status = main()
  File "/usr/lib/python3.10/site-packages/httpie/core.py", line 162, in main
    return raw_main(
  File "/usr/lib/python3.10/site-packages/httpie/core.py", line 77, in raw_main
    parsed_args = parser.parse_args(
  File "/usr/lib/python3.10/site-packages/httpie/cli/argparser.py", line 159, in parse_args
    self.args, no_options = super().parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2095, in _parse_known_args
    self.error(_('the following arguments are required: %s') %
  File "/usr/lib/python3.10/site-packages/httpie/cli/argparser.py", line 601, in error
    self.print_usage(sys.stderr)
  File "/usr/lib/python3.10/site-packages/httpie/cli/argparser.py", line 576, in print_usage
    from rich.text import Text
ModuleNotFoundError: No module named 'rich'
```

**Comment by mortenlj** [comment]
Fixed in 8cf4af43a97dd4c14834c09676adbbc2ad1f0ef8
